### PR TITLE
Add 4 restaurants for HSL Pasila team

### PR DESCRIPTION
**Pull request by hungneox**
- Factory Vallila
- Savor
- Viherlatva
- Antell Akavatalo

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks! First thing, please could you format the code with Black?

```sh
pip install -U black && black .
```

**Comment by hugovk** [comment]
Thanks! Next up, there's a `KeyError`:

```
p lunchbot.py --dry-run --restaurants all
Namespace(dry_run=True, json=False, restaurants=['all'], user=None)
:PihkaKasarmi: Pihka Kasarmi
Mausteista maissikanakeittoa ja korianterijugurttia
Blinejä sienisalaatilla, suolakurkulla ja sipulilla
Härkästifadoa, paahdettua perunaa ja persiljaa
Puolukka-karpalopiirakkaa
Aamupuuro: luomuohrapuuroa
11-14 30m
https://www.lounaat.info/lounas/pihka-kasarmi/helsinki

:TheCock: The Cock
Katso päivän lounaslista ravintolan sivuilta!
11-14:30 140m
https://www.lounaat.info/lounas/the-cock/helsinki

Traceback (most recent call last):
  File "lunchbot.py", line 512, in <module>
    restaurant, restaurant_function, args.dry_run, args.user
  File "lunchbot.py", line 401, in do_restaurant
    ret = restaurant_function()
  File "lunchbot.py", line 356, in lunch_viherlatva
    return lunch_pasila("Fazer Food & Co Viherlatva")
  File "lunchbot.py", line 370, in lunch_pasila
    url = LOUNAAT_PASILA_URLS[restaurant]
KeyError: 'Fazer Food & Co Viherlatva'
```

**Comment by hungneox** [comment]
> Thanks! Next up, there's a `KeyError`:
> 
> ```
> $ p lunchbot.py --dry-run --restaurants all
> Namespace(dry_run=True, json=False, restaurants=['all'], user=None)
> :PihkaKasarmi: Pihka Kasarmi
> Mausteista maissikanakeittoa ja korianterijugurttia
> Blinejä sienisalaatilla, suolakurkulla ja sipulilla
> Härkästifadoa, paahdettua perunaa ja persiljaa
> Puolukka-karpalopiirakkaa
> Aamupuuro: luomuohrapuuroa
> 11-14 30m
> https://www.lounaat.info/lounas/pihka-kasarmi/helsinki
> 
> :TheCock: The Cock
> Katso päivän lounaslista ravintolan sivuilta!
> 11-14:30 140m
> https://www.lounaat.info/lounas/the-cock/helsinki
> 
> Traceback (most recent call last):
>   File "lunchbot.py", line 512, in <module>
>     restaurant, restaurant_function, args.dry_run, args.user
>   File "lunchbot.py", line 401, in do_restaurant
>     ret = restaurant_function()
>   File "lunchbot.py", line 356, in lunch_viherlatva
>     return lunch_pasila("Fazer Food & Co Viherlatva")
>   File "lunchbot.py", line 370, in lunch_pasila
>     url = LOUNAAT_PASILA_URLS[restaurant]
> KeyError: 'Fazer Food & Co Viherlatva'
> ```

Thanks for checking my PR. I've fixed the issue.

**Comment by hugovk** [comment]
Looks good!

I merged in some CI changes from `master` and added `--kassu` and `--pasila` shortcuts to make it easier to run.

We could possibly refactor some bits later, but let's get this merged and connected to Slack!

**Pull request merged**
